name: teste-cicd

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configura JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build do projeto Maven
      run: mvn clean package -DskipTests

    - name: Verifica versão do Docker Compose
      run: docker compose version

    - name: Sobe containers com Docker Compose
      run: docker compose up -d

    - name: Executa testes unitários
      run: mvn -B verify
